/* 由 tools/build_seed.py 產生，請勿手改。
   來源：FC.xlsx + 115/09 台新／寰宇／國泰CUBE／聯邦、115/03 與 115/09 富邦 信用卡帳單 */
window.SEED = {
 "categories": [
  "FC月費",
  "FC年費",
  "扭蛋",
  "周邊商品",
  "專輯唱片",
  "演唱會票券",
  "餐飲",
  "交通",
  "旅遊住宿",
  "生活用品",
  "服飾美妝",
  "百貨購物",
  "電信網路",
  "訂閱服務",
  "醫療保健",
  "運動健身",
  "稅費保險",
  "回饋折抵",
  "其他"
 ],
 "cards": [
  "台新Richart 3208",
  "台新Richart 0602",
  "寰宇卡 2007",
  "國泰CUBE 3624",
  "國泰CUBE 2225",
  "聯邦M悠遊鈦 0206",
  "聯邦賴點卡 9908",
  "LINE Bank 1308",
  "4511 卡",
  "6357 卡",
  "富邦MASTER 6848",
  "富邦MASTER 0969"
 ],
 "records": [
  {
   "date": "2026-04-06",
   "postDate": "2026-04-13",
   "item": "TAKASE TOYA OFFICIAL FANCLUB 月額費",
   "twd": 241,
   "currency": "JPY",
   "amount": 1200,
   "fee": 4,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "TT000274",
   "nextDue": "",
   "category": "FC月費",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-05-06",
   "postDate": "2026-05-12",
   "item": "TAKASE TOYA OFFICIAL FANCLUB 月額費",
   "twd": 244,
   "currency": "JPY",
   "amount": 1200,
   "fee": 4,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "TT000274",
   "nextDue": "",
   "category": "FC月費",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-06",
   "postDate": "2026-07-14",
   "item": "TAKASE TOYA OFFICIAL FANCLUB 月額費",
   "twd": 239,
   "currency": "JPY",
   "amount": 1200,
   "fee": 4,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "TT000274",
   "nextDue": "",
   "category": "FC月費",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-08-06",
   "postDate": "2026-08-12",
   "item": "TAKASE TOYA OFFICIAL FANCLUB 月額費",
   "twd": 248,
   "currency": "JPY",
   "amount": 1200,
   "fee": 4,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "TT000274",
   "nextDue": "",
   "category": "FC月費",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-06",
   "postDate": "2026-07-14",
   "item": "Fumiya Sato Official Site「Maison Fumiya」 年額費",
   "twd": 1716,
   "currency": "JPY",
   "amount": 8610,
   "fee": 26,
   "card": "聯邦M悠遊鈦 0206",
   "note": "2026.07.06 ~ 2027.07.06",
   "memberId": "FS000064",
   "nextDue": "2027-07-06",
   "category": "FC年費",
   "artist": "Fumiya Sato"
  },
  {
   "date": "2026-05-25",
   "postDate": "2026-05-29",
   "item": "EXIMBAY*WEVERSESEOUL BTS ARMY MEMBERSHIP CARD KRW22,727",
   "twd": 501,
   "currency": "KRW",
   "amount": 23863,
   "fee": 8,
   "card": "台新Richart 0602",
   "note": "2026.05.24 ~ 2027.05.24",
   "memberId": "BA173619663",
   "nextDue": "2027-05-24",
   "category": "FC年費",
   "artist": "BTS"
  },
  {
   "date": "2026-07-11",
   "postDate": "2026-07-14",
   "item": "TOSS*KQENTERTAINMENTSEOUL ATEEZ ATINY MEMBERSHIP",
   "twd": 430,
   "currency": "KRW",
   "amount": 20000,
   "fee": 6,
   "card": "台新Richart 0602",
   "note": "2026.07.10 ~ 2027.07.10",
   "memberId": "BMM9RM",
   "nextDue": "2027-07-10",
   "category": "FC年費",
   "artist": "ATEEZ"
  },
  {
   "date": "2026-07-09",
   "postDate": "2026-07-13",
   "item": "CREEPY NUTS FAN APPSHIBUY",
   "twd": 99,
   "currency": "JPY",
   "amount": 500,
   "fee": 1,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "FC月費",
   "artist": "CREEPY NUTS"
  },
  {
   "date": "2026-08-09",
   "postDate": "2026-08-11",
   "item": "CREEPY NUTS FAN APPSHIBUY",
   "twd": 103,
   "currency": "JPY",
   "amount": 500,
   "fee": 2,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "FC月費",
   "artist": "CREEPY NUTS"
  },
  {
   "date": "2026-06-13",
   "postDate": "2026-06-18",
   "item": "TAKASE TOYA OFFICIAL FAN NAGOYA",
   "twd": 992,
   "currency": "JPY",
   "amount": 5000,
   "fee": 15,
   "card": "台新Richart 0602",
   "note": "扭蛋",
   "memberId": "",
   "nextDue": "",
   "category": "扭蛋",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-10",
   "postDate": "2026-07-16",
   "item": "TAKASE TOYA OFFICIAL FAN NAGOYA",
   "twd": 99,
   "currency": "JPY",
   "amount": 500,
   "fee": 1,
   "card": "聯邦賴點卡 9908",
   "note": "扭蛋",
   "memberId": "",
   "nextDue": "",
   "category": "扭蛋",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-10",
   "postDate": "2026-07-16",
   "item": "TAKASE TOYA OFFICIAL FAN NAGOYA",
   "twd": 99,
   "currency": "JPY",
   "amount": 500,
   "fee": 1,
   "card": "聯邦賴點卡 9908",
   "note": "扭蛋",
   "memberId": "",
   "nextDue": "",
   "category": "扭蛋",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-10",
   "postDate": "2026-07-16",
   "item": "TAKASE TOYA OFFICIAL FAN NAGOYA",
   "twd": 496,
   "currency": "JPY",
   "amount": 2500,
   "fee": 7,
   "card": "聯邦賴點卡 9908",
   "note": "扭蛋",
   "memberId": "",
   "nextDue": "",
   "category": "扭蛋",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-07-10",
   "postDate": "2026-07-16",
   "item": "TAKASE TOYA OFFICIAL FAN NAGOYA",
   "twd": 992,
   "currency": "JPY",
   "amount": 5000,
   "fee": 15,
   "card": "聯邦賴點卡 9908",
   "note": "扭蛋",
   "memberId": "",
   "nextDue": "",
   "category": "扭蛋",
   "artist": "TAKASE TOYA"
  },
  {
   "date": "2026-08-19",
   "postDate": "2026-08-25",
   "item": "ONE ROOM BACK NUMBER FC TOKYO gold key",
   "twd": 1384,
   "currency": "JPY",
   "amount": 6900,
   "fee": 21,
   "card": "台新Richart 0602",
   "note": "2027.08.31",
   "memberId": "660787",
   "nextDue": "2027-08-31",
   "category": "FC年費",
   "artist": "back number"
  },
  {
   "date": "2026-08-24",
   "postDate": "2026-08-28",
   "item": "OFFICIALHIGEDANDISM FC TOKYO STAND BY YOU",
   "twd": 1327,
   "currency": "JPY",
   "amount": 6600,
   "fee": 20,
   "card": "台新Richart 0602",
   "note": "2027.08.31",
   "memberId": "E101185182052",
   "nextDue": "2027-08-31",
   "category": "FC年費",
   "artist": "Official髭男dism"
  },
  {
   "date": "2026-09-09",
   "postDate": "",
   "item": "PRIMAL FOOTMARK 2026 ONE OK ROCK",
   "twd": null,
   "currency": "JPY",
   "amount": 4490,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "尚未入帳，本幣待補",
   "memberId": "",
   "nextDue": "",
   "category": "FC年費",
   "artist": "ONE OK ROCK"
  },
  {
   "date": "2026-06-27",
   "postDate": "2026-06-30",
   "item": "WEVERSE TOKYO Mrs. GREEN APPLE<ゼンジン未到とイ/ミュータブル~間奏編~>HD Single-view(Live+Delayed Streaming)",
   "twd": 987,
   "currency": "JPY",
   "amount": 5000,
   "fee": 15,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": "Mrs. GREEN APPLE"
  },
  {
   "date": "2026-07-25",
   "postDate": "2026-07-29",
   "item": "TOWER RECORDS  ONE OK ROCK DETOX",
   "twd": 1234,
   "currency": "JPY",
   "amount": 6240,
   "fee": 18,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "專輯唱片",
   "artist": "ONE OK ROCK"
  },
  {
   "date": "2026-08-20",
   "postDate": "2026-08-21",
   "item": "ONE OK ROCK US 黑膠",
   "twd": 2103,
   "currency": "USD",
   "amount": 65.97,
   "fee": 32,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "專輯唱片",
   "artist": "ONE OK ROCK"
  },
  {
   "date": "2026-06-07",
   "postDate": "2026-06-09",
   "item": "CHOGAKUSEI.STORESHIBUY",
   "twd": 2036,
   "currency": "JPY",
   "amount": 10300,
   "fee": 30,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "周邊商品",
   "artist": "超学生"
  },
  {
   "date": "2026-07-13",
   "postDate": "2026-07-20",
   "item": "SP NATORIUM STOREA9467 MINATO",
   "twd": 5259,
   "currency": "JPY",
   "amount": 26480,
   "fee": 79,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "周邊商品",
   "artist": "ナトリ"
  },
  {
   "date": "2026-08-10",
   "postDate": "2026-08-11",
   "item": "SP NATORIUM STOREMINATO",
   "twd": 2093,
   "currency": "JPY",
   "amount": 10180,
   "fee": 31,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "周邊商品",
   "artist": "ナトリ"
  },
  {
   "date": "2026-08-11",
   "postDate": "2026-08-13",
   "item": "SP NATORIUM STOREMINATO",
   "twd": 2576,
   "currency": "JPY",
   "amount": 12580,
   "fee": 39,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "周邊商品",
   "artist": "ナトリ"
  },
  {
   "date": "2026-08-07",
   "postDate": "2026-08-12",
   "item": "中油－台中公園路站",
   "twd": 164,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-08-07",
   "postDate": "2026-08-11",
   "item": "信用卡消費折抵_中油－台中公園路站",
   "twd": -49,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-08-16",
   "postDate": "2026-08-20",
   "item": "連支*犀牛創 RHIN Taipei",
   "twd": 1500,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-17",
   "postDate": "2026-08-21",
   "item": "連支*台灣大創 Taipei",
   "twd": 98,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-20",
   "postDate": "2026-08-26",
   "item": "連支*GU網路商店 Taipei",
   "twd": 1870,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "服飾美妝",
   "artist": ""
  },
  {
   "date": "2026-08-24",
   "postDate": "2026-08-28",
   "item": "連支*日月亭股份有限公司 Taipei",
   "twd": 75,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 3208",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-08-07",
   "postDate": "2026-08-10",
   "item": "Patreon* Membership",
   "twd": 305,
   "currency": "USD",
   "amount": 9.45,
   "fee": 5,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "訂閱服務",
   "artist": ""
  },
  {
   "date": "2026-08-07",
   "postDate": "2026-08-11",
   "item": "信用卡消費折抵_Patreon* Membership",
   "twd": -91,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-08-09",
   "postDate": "2026-08-24",
   "item": "信用卡消費折抵_CREEPY NUTS FAN APP",
   "twd": -30,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": "CREEPY NUTS"
  },
  {
   "date": "2026-08-21",
   "postDate": "2026-08-24",
   "item": "ANTHROPIC* CLAUDE SUB",
   "twd": 638,
   "currency": "USD",
   "amount": 20.0,
   "fee": 9,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "訂閱服務",
   "artist": ""
  },
  {
   "date": "2026-08-21",
   "postDate": "2026-08-24",
   "item": "信用卡消費折抵_ANTHROPIC* CLAUDE SUB",
   "twd": -191,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-08-28",
   "postDate": "2026-09-01",
   "item": "SITE FEE DWANGO TOKYO",
   "twd": 110,
   "currency": "JPY",
   "amount": 550,
   "fee": 2,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "FC月費",
   "artist": ""
  },
  {
   "date": "2026-08-28",
   "postDate": "2026-08-31",
   "item": "寬宏藝術經紀股份有限公司（網路）",
   "twd": 2880,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": ""
  },
  {
   "date": "2026-08-31",
   "postDate": "2026-09-03",
   "item": "中油－草屯站",
   "twd": 169,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-08-31",
   "postDate": "2026-08-31",
   "item": "臺北大眾捷運股份有限公司",
   "twd": 40,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-09-01",
   "postDate": "2026-09-07",
   "item": "ARTIST SITE TOKYO",
   "twd": 88,
   "currency": "JPY",
   "amount": 440,
   "fee": 1,
   "card": "台新Richart 0602",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "FC月費",
   "artist": ""
  },
  {
   "date": "2026-08-04",
   "postDate": "2026-08-04",
   "item": "現金點數扣抵",
   "twd": -350,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-07-31",
   "postDate": "2026-08-03",
   "item": "遠傳－Ｔｉｃｋｅｔ　Ｐｌｕｓ　售票+",
   "twd": 1400,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": ""
  },
  {
   "date": "2026-08-04",
   "postDate": "2026-08-06",
   "item": "大鴻藝術股份有限公司",
   "twd": 1600,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": ""
  },
  {
   "date": "2026-08-06",
   "postDate": "2026-08-10",
   "item": "國立自然科學博物館",
   "twd": 240,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-08",
   "postDate": "2026-08-11",
   "item": "ＶＥＲＶＥ",
   "twd": 4520,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-10",
   "postDate": "2026-08-12",
   "item": "街口電支－ＡＰＰ信用卡儲值",
   "twd": 320,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-14",
   "postDate": "2026-08-17",
   "item": "遠傳－Ｔｉｃｋｅｔ　Ｐｌｕｓ　售票+",
   "twd": 1300,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": ""
  },
  {
   "date": "2026-08-17",
   "postDate": "2026-08-19",
   "item": "大樹連鎖藥局－草屯碧山門市",
   "twd": 155,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "醫療保健",
   "artist": ""
  },
  {
   "date": "2026-08-19",
   "postDate": "2026-08-24",
   "item": "遠傳－Ｔｉｃｋｅｔ　Ｐｌｕｓ　售票+",
   "twd": 2600,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "演唱會票券",
   "artist": ""
  },
  {
   "date": "2026-08-22",
   "postDate": "2026-08-24",
   "item": "街口電支－ＡＰＰ信用卡儲值",
   "twd": 90,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-30",
   "postDate": "2026-09-01",
   "item": "統一金流－享印生活股份有限公司",
   "twd": 150,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-30",
   "postDate": "2026-09-01",
   "item": "統一金流－享印生活股份有限公司",
   "twd": 150,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-08-30",
   "postDate": "2026-08-31",
   "item": "京都柚子豚骨拉麵研究中心－中山本店",
   "twd": 320,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "寰宇卡 2007",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-07-25",
   "postDate": "2026-07-29",
   "item": "台灣角川股份有限公司",
   "twd": 1229,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-07-26",
   "postDate": "2026-07-29",
   "item": "ICASH加值－桃園捷運新",
   "twd": 500,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-07-26",
   "postDate": "2026-07-28",
   "item": "宏匯廣場",
   "twd": 70,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-07-26",
   "postDate": "2026-07-28",
   "item": "宏匯廣場",
   "twd": 238,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-07-26",
   "postDate": "2026-07-28",
   "item": "宏匯廣場",
   "twd": 238,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-07-26",
   "postDate": "2026-07-28",
   "item": "宏匯廣場",
   "twd": 140,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-07-30",
   "postDate": "2026-08-03",
   "item": "GOOGLE *VISA0001",
   "twd": 479,
   "currency": "TWD",
   "amount": 479,
   "fee": 7,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "訂閱服務",
   "artist": ""
  },
  {
   "date": "2026-08-02",
   "postDate": "2026-08-05",
   "item": "ＬａＬａｐｏｒｔ台中",
   "twd": 2790,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-08-02",
   "postDate": "2026-08-05",
   "item": "點數折抵__ＬａＬａｐｏｒｔ",
   "twd": -117,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-08-02",
   "postDate": "2026-08-05",
   "item": "ＬａＬａｐｏｒｔ台中",
   "twd": 80,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-08-02",
   "postDate": "2026-08-05",
   "item": "ＬａＬａｐｏｒｔ台中",
   "twd": 198,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-08-13",
   "postDate": "2026-08-14",
   "item": "輕鬆繳遠傳電 905****63",
   "twd": 1079,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "電信網路",
   "artist": ""
  },
  {
   "date": "2026-08-13",
   "postDate": "2026-08-14",
   "item": "輕鬆繳遠傳電 976****61",
   "twd": 218,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "電信網路",
   "artist": ""
  },
  {
   "date": "2026-08-15",
   "postDate": "2026-08-18",
   "item": "宏匯廣場",
   "twd": 249,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-08-16",
   "postDate": "2026-08-19",
   "item": "無印良品－文心門市",
   "twd": 79,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-22",
   "postDate": "2026-08-26",
   "item": "統一時代百貨台北店",
   "twd": 3490,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 3624",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "百貨購物",
   "artist": ""
  },
  {
   "date": "2026-08-01",
   "postDate": "2026-08-03",
   "item": "樂購蝦皮－ｏｕｃｈ＿ｔ",
   "twd": 980,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-05",
   "postDate": "2026-08-07",
   "item": "樂購蝦皮－１８２３９０",
   "twd": 480,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-08",
   "postDate": "2026-08-10",
   "item": "樂購蝦皮－ｏｕｃｈ＿ｔ（退款）",
   "twd": -253,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-11",
   "postDate": "2026-08-13",
   "item": "樂購蝦皮－嘉佑商行",
   "twd": 378,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-11",
   "postDate": "2026-08-17",
   "item": "樂購蝦皮－榮郁國際有限",
   "twd": 810,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-17",
   "postDate": "2026-08-19",
   "item": "樂購蝦皮－ｋａｉｔａｒ",
   "twd": 365,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-17",
   "postDate": "2026-08-19",
   "item": "樂購蝦皮－蝦皮直營生活",
   "twd": 216,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-18",
   "postDate": "2026-08-20",
   "item": "樂購蝦皮－ｂａｉｍｏｍ",
   "twd": 379,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-18",
   "postDate": "2026-08-20",
   "item": "樂購蝦皮－ｋｅｍｅ＿ｇ",
   "twd": 257,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-18",
   "postDate": "2026-08-20",
   "item": "樂購蝦皮－亞吉聯創有限",
   "twd": 630,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-18",
   "postDate": "2026-08-20",
   "item": "樂購蝦皮－ｓ３６１８２",
   "twd": 318,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-22",
   "postDate": "2026-08-26",
   "item": "樂購蝦皮－ｃｈａｒｌｉ",
   "twd": 268,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-22",
   "postDate": "2026-08-24",
   "item": "樂購蝦皮－ａｚｓ２０３",
   "twd": 246,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "國泰CUBE 2225",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-05",
   "postDate": "2026-08-10",
   "item": "Ｈａｍｉ　Ｐｏｉｎｔ",
   "twd": 1532,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "4511 卡",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "電信網路",
   "artist": ""
  },
  {
   "date": "2026-08-16",
   "postDate": "2026-08-20",
   "item": "健身工廠－草屯廠",
   "twd": 888,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "4511 卡",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "運動健身",
   "artist": ""
  },
  {
   "date": "2026-05-23",
   "postDate": "2026-07-28",
   "item": "綜所稅單筆０３－０６",
   "twd": 330,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "6357 卡",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "稅費保險",
   "artist": ""
  },
  {
   "date": "2026-08-18",
   "postDate": "2026-08-24",
   "item": "全國加油站樹王自助",
   "twd": 130,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "6357 卡",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-08-23",
   "postDate": "2026-08-24",
   "item": "台灣薩莉亞餐飲股份有限",
   "twd": 270,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "6357 卡",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-07-15",
   "postDate": "2026-07-15",
   "item": "刷卡現金回饋－聯邦Ｍ國外加碼",
   "twd": -7,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "回饋折抵",
   "artist": ""
  },
  {
   "date": "2026-07-25",
   "postDate": "2026-07-28",
   "item": "卡夫人背包客棧",
   "twd": 1979,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "旅遊住宿",
   "artist": ""
  },
  {
   "date": "2026-07-25",
   "postDate": "2026-07-29",
   "item": "國光汽車客運－網路",
   "twd": 1344,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-07-27",
   "postDate": "2026-07-29",
   "item": "連支＊日月亭股份有限公",
   "twd": 75,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-08-07",
   "postDate": "2026-08-12",
   "item": "國光汽車客運－網路",
   "twd": 732,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "交通",
   "artist": ""
  },
  {
   "date": "2026-08-08",
   "postDate": "2026-08-12",
   "item": "台灣青旅",
   "twd": 990,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦M悠遊鈦 0206",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "旅遊住宿",
   "artist": ""
  },
  {
   "date": "2026-08-06",
   "postDate": "2026-08-11",
   "item": "Yibor Technology Co., Lim HONG KONG",
   "twd": 10799,
   "currency": "TWD",
   "amount": 10799,
   "fee": 162,
   "card": "LINE Bank 1308",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "其他",
   "artist": ""
  },
  {
   "date": "2026-07-19",
   "postDate": "2026-07-21",
   "item": "連支＊５０嵐－穎冠",
   "twd": 155,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦賴點卡 9908",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-08-01",
   "postDate": "2026-08-05",
   "item": "連加＊爬咖啡",
   "twd": 150,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦賴點卡 9908",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-08-06",
   "postDate": "2026-08-08",
   "item": "連支＊厭世夯肉",
   "twd": 208,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦賴點卡 9908",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-08-04",
   "postDate": "2026-08-10",
   "item": "連加＊Ｓｉｓ・Ｔｉｎｇ",
   "twd": 1200,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "聯邦賴點卡 9908",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "餐飲",
   "artist": ""
  },
  {
   "date": "2026-02-13",
   "postDate": "2026-02-23",
   "item": "富邦momo-EC",
   "twd": 835,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-02-16",
   "postDate": "2026-02-23",
   "item": "富邦momo-EC",
   "twd": 1270,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-02-22",
   "postDate": "2026-02-24",
   "item": "富邦momo-EC",
   "twd": 764,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-02-23",
   "postDate": "2026-02-26",
   "item": "台灣人壽續期保費",
   "twd": 17297,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "年繳保費",
   "memberId": "",
   "nextDue": "",
   "category": "稅費保險",
   "artist": ""
  },
  {
   "date": "2026-02-25",
   "postDate": "2026-03-03",
   "item": "全球人壽８８０００４６０６００",
   "twd": 14602,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "年繳保費",
   "memberId": "",
   "nextDue": "",
   "category": "稅費保險",
   "artist": ""
  },
  {
   "date": "2026-02-25",
   "postDate": "2026-03-02",
   "item": "富邦momo-EC",
   "twd": 815,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-02-26",
   "postDate": "2026-03-02",
   "item": "富邦momo-EC",
   "twd": 797,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-06",
   "postDate": "2026-08-10",
   "item": "富邦momo-EC",
   "twd": 744,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-08-21",
   "postDate": "2026-08-24",
   "item": "富邦momo-EC",
   "twd": 1930,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 6848",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  },
  {
   "date": "2026-09-05",
   "postDate": "2026-09-07",
   "item": "好市多北台中店",
   "twd": 99,
   "currency": "",
   "amount": 0,
   "fee": 0,
   "card": "富邦MASTER 0969",
   "note": "",
   "memberId": "",
   "nextDue": "",
   "category": "生活用品",
   "artist": ""
  }
 ],
 "subs": [
  {
   "name": "TAKASE TOYA OFFICIAL FANCLUB 月額費",
   "amount": 252,
   "cycle": "month",
   "card": "聯邦M悠遊鈦 0206",
   "category": "FC月費",
   "active": true,
   "artist": "TAKASE TOYA",
   "memberId": "TT000274",
   "nextDue": "",
   "note": ""
  },
  {
   "name": "SITE FEE DWANGO TOKYO",
   "amount": 112,
   "cycle": "month",
   "card": "台新Richart 0602",
   "category": "FC月費",
   "active": true,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": ""
  },
  {
   "name": "ARTIST SITE TOKYO",
   "amount": 89,
   "cycle": "month",
   "card": "台新Richart 0602",
   "category": "FC月費",
   "active": true,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": ""
  },
  {
   "name": "ATEEZ Fromm／myArti",
   "amount": 320,
   "cycle": "month",
   "card": "",
   "category": "FC月費",
   "active": true,
   "artist": "ATEEZ",
   "memberId": "",
   "nextDue": "",
   "note": "115/09 新訂，尚未出現在帳單"
  },
  {
   "name": "Apple Store iCloud 200G",
   "amount": 90,
   "cycle": "month",
   "card": "",
   "category": "訂閱服務",
   "active": true,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": "115/09 新訂，尚未出現在帳單"
  },
  {
   "name": "GOOGLE *VISA0001",
   "amount": 486,
   "cycle": "month",
   "card": "國泰CUBE 3624",
   "category": "訂閱服務",
   "active": true,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": ""
  },
  {
   "name": "ANTHROPIC* CLAUDE SUB",
   "amount": 647,
   "cycle": "month",
   "card": "台新Richart 0602",
   "category": "訂閱服務",
   "active": true,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": ""
  },
  {
   "name": "CREEPY NUTS FAN APPSHIBUY",
   "amount": 105,
   "cycle": "month",
   "card": "台新Richart 0602",
   "category": "FC月費",
   "active": false,
   "artist": "CREEPY NUTS",
   "memberId": "",
   "nextDue": "",
   "note": "115/09 已停訂"
  },
  {
   "name": "Patreon* Membership",
   "amount": 310,
   "cycle": "month",
   "card": "台新Richart 0602",
   "category": "訂閱服務",
   "active": false,
   "artist": "",
   "memberId": "",
   "nextDue": "",
   "note": "115/09 已停訂"
  },
  {
   "name": "Fumiya Sato Official Site「Maison Fumiya」 年額費",
   "amount": 1742,
   "cycle": "year",
   "card": "聯邦M悠遊鈦 0206",
   "category": "FC年費",
   "active": true,
   "artist": "Fumiya Sato",
   "memberId": "FS000064",
   "nextDue": "2027-07-06",
   "note": ""
  },
  {
   "name": "EXIMBAY*WEVERSESEOUL BTS ARMY MEMBERSHIP CARD KRW22,727",
   "amount": 509,
   "cycle": "year",
   "card": "台新Richart 0602",
   "category": "FC年費",
   "active": true,
   "artist": "BTS",
   "memberId": "BA173619663",
   "nextDue": "2027-05-24",
   "note": ""
  },
  {
   "name": "TOSS*KQENTERTAINMENTSEOUL ATEEZ ATINY MEMBERSHIP",
   "amount": 436,
   "cycle": "year",
   "card": "台新Richart 0602",
   "category": "FC年費",
   "active": true,
   "artist": "ATEEZ",
   "memberId": "BMM9RM",
   "nextDue": "2027-07-10",
   "note": ""
  },
  {
   "name": "ONE ROOM BACK NUMBER FC TOKYO gold key",
   "amount": 1405,
   "cycle": "year",
   "card": "台新Richart 0602",
   "category": "FC年費",
   "active": true,
   "artist": "back number",
   "memberId": "660787",
   "nextDue": "2027-08-31",
   "note": ""
  },
  {
   "name": "OFFICIALHIGEDANDISM FC TOKYO STAND BY YOU",
   "amount": 1347,
   "cycle": "year",
   "card": "台新Richart 0602",
   "category": "FC年費",
   "active": true,
   "artist": "Official髭男dism",
   "memberId": "E101185182052",
   "nextDue": "2027-08-31",
   "note": ""
  },
  {
   "name": "PRIMAL FOOTMARK 2026 ONE OK ROCK",
   "amount": 0,
   "cycle": "year",
   "card": "台新Richart 0602",
   "category": "FC年費",
   "active": true,
   "artist": "ONE OK ROCK",
   "memberId": "",
   "nextDue": "2027-09-09",
   "note": "115/09 刷卡，金額待帳單確認"
  }
 ],
 "installments": [
  {
   "name": "26/05 帳單分期",
   "card": "台新Richart 3208",
   "total": 20000,
   "monthly": 3346,
   "interest": 52,
   "remaining": 6718,
   "apr": 4.77
  },
  {
   "name": "26/06 帳單分期",
   "card": "台新Richart 3208",
   "total": 4978,
   "monthly": 826,
   "interest": 19,
   "remaining": 2497,
   "apr": 4.77
  },
  {
   "name": "26/07 帳單分期",
   "card": "台新Richart 3208",
   "total": 7770,
   "monthly": 642,
   "interest": 16,
   "remaining": 6491,
   "apr": 6.58
  },
  {
   "name": "BIC CAMERA TENJIN2",
   "card": "台新Richart 3208",
   "total": 23352,
   "monthly": 1942,
   "interest": 24,
   "remaining": 15618,
   "apr": 1.88
  },
  {
   "name": "新光產物保險",
   "card": "台新Richart 0602",
   "total": 1115,
   "monthly": 92,
   "interest": 0,
   "remaining": 736,
   "apr": 0.0
  },
  {
   "name": "拓元票務服務",
   "card": "台新Richart 0602",
   "total": 9580,
   "monthly": 795,
   "interest": 11,
   "remaining": 7204,
   "apr": 1.88
  },
  {
   "name": "遠傳－Ticket Plus",
   "card": "台新Richart 0602",
   "total": 3200,
   "monthly": 265,
   "interest": 4,
   "remaining": 2407,
   "apr": 1.88
  },
  {
   "name": "藍新－KKTIX售票報名平",
   "card": "台新Richart 0602",
   "total": 5800,
   "monthly": 481,
   "interest": 7,
   "remaining": 4361,
   "apr": 1.88
  },
  {
   "name": "富邦人壽（保費分期）",
   "card": "富邦MASTER 6848",
   "total": 13145,
   "monthly": 1095,
   "interest": 0,
   "remaining": 5475,
   "apr": 0.0
  }
 ],
 "budget": {
  "income": 35000,
  "savings": 0,
  "fixed": [
   {
    "name": "皮膚科",
    "amount": 2000
   },
   {
    "name": "其他固定支出",
    "amount": 5000
   },
   {
    "name": "電信費（遠傳兩門號）",
    "amount": 1297
   },
   {
    "name": "保險預留（台壽＋全球 年 31,899）",
    "amount": 2658
   }
  ],
  "excludeCats": [
   "稅費保險"
  ]
 }
};
